### ISSUE TITLE
2017 年 9 月

### ISSUE THREAD

**Issue by bizhong** [bizhong/frontend#2]
# 列表项目滑到顶部列表项目头部固定

```html
<ul class="lanbizhong">
  <li class="lanbizhong-item">
    <div class="lanbizhong-item-header"></div>
    <div class="lanbizhong-item-content"></div>
  </li>
  <!-- ... -->
</ul>
```
```css
.lanbizhong {
  overflow-x: hidden;
  overflow-y: auto;
  list-style: none;
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 4;
  margin: 0;
  padding: 0;
  -webkit-overflow-scrolling: touch;
  overflow-scrolling: touch;
}
.lanbizhong-item {
  position: relative;
  z-index: 3;
}
.lanbizhong-item-header {
  position: absolute;
  z-index: 2;
  width: 100%;
  height: 32px;
  background: #f2f2f2;
}
.lanbizhong-item-header.fixed {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 1;
}
.lanbizhong-item-content {
  padding-top: 32px;
  width: 100%;
  min-height: 666px;
  background: #fff;
}
```
```javascript
// jQuery
$('.lanbizhong').scroll(function() {
  // 列表项目滑到顶部列表项目头部固定
  $('.lanbizhong-item-header').each(function(i) {
    var self = $(this).parent('.lanbizhong-item');
    var itemHeight = self.height();
    var itemTop = self.offset().top;
    if (itemTop > -itemHeight && itemTop <= 0) {
      $(this).addClass('fixed');
    } else {
      $(this).removeClass('fixed');
    }
  });
});
```

**Comment by bizhong** [comment]
# 列表项目滑到顶部列表项目头部固定

列表项目滑到顶部列表项目头部固定。

```html
<ul class="lanbizhong">
  <li class="lanbizhong-item">
    <div class="lanbizhong-item-header"></div>
    <div class="lanbizhong-item-content"></div>
  </li>
  <!-- ... -->
</ul>
```
```css
.lanbizhong {
  overflow-x: hidden;
  overflow-y: auto;
  list-style: none;
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 2;
  margin: 0;
  padding: 0;
  -webkit-overflow-scrolling: touch;
  overflow-scrolling: touch;
}
.lanbizhong-item {
  position: relative;
  z-index: 1;
}
.lanbizhong-item-header {
  position: absolute;
  z-index: 0;
  width: 100%;
  height: 32px;
  background: #f2f2f2;
}
.lanbizhong-item-header.fixed {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 1;
}
.lanbizhong-item-content {
  padding-top: 32px;
  width: 100%;
  min-height: 666px;
  background: #fff;
}
```
```javascript
// jQuery
$('.lanbizhong').scroll(function() {
  // 列表项目滑到顶部列表项目头部固定
  $('.lanbizhong-item-header').each(function(i) {
    var self = $(this).parent('.lanbizhong-item');
    var itemHeight = self.height();
    var itemTop = self.offset().top;
    if (itemTop > -itemHeight && itemTop <= 0) {
      $(this).addClass('fixed');
    } else {
      $(this).removeClass('fixed');
    }
  });
});
```

**Comment by bizhong** [comment]
# :ideograph_advantage:

项目开发阶段，**前端**要和**设计**、**后端**沟通到位。

> **设计** :point_left: **前端** :point_right: **后端**

**Comment by bizhong** [comment]
# CSS 变量

CSS 变量是由 CSS 作者定义的实体，其中包含要在整个文档中重复使用的特定值。使用自定义属性来设置变量名，并使用特定的 `var()` 来访问。

```css
:root {
  --main-bg-color: #fff;
}
.lanbizhong {
  background-color: var(--main-bg-color);
}
```

教程：

- [使用CSS变量 - CSS | MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_variables)
- [CSS 变量教程 - 阮一峰的网络日志](http://www.ruanyifeng.com/blog/2017/05/css-variables.html)

浏览器支持：

- [Can I use... Support tables for HTML5, CSS3, etc](http://caniuse.com/#search=css%20var)
