### ISSUE TITLE
2017 年 12 月

### ISSUE THREAD

**Issue by bizhong** [bizhong/frontend#5]
# Tab 边框简写

```html
<nav class="tabs">
  <a class="tabs-tab active" href="#beijing">北京</a>
  <a class="tabs-tab" href="#shanghai">上海</a>
  <a class="tabs-tab" href="#guangzhou">广州</a>
  <a class="tabs-tab" href="#shenzhen">深圳</a>
</nav>
```

```css
.tabs {
  font-size: 0;
}
.tabs-tab {
  display: inline-block;
  padding: 0 24px;
  border: 1px solid #e0e0e0;
  font-size: 14px;
  line-height: 32px;
  text-decoration: none;
  color: rgba(0, 0, 0, .54);
}
.tabs-tab.active,
.tabs-tab:hover {
  border-color: #333;
  color: rgba(0, 0, 0, .87);
  background-color: #f2f2f2;
}
```

**问题**：相邻 Tab `border-width` 为 `2px`。

虽然 `border-left: 0;` 或 `border-right: 0;` 可以解决上述问题，但是 `hover` 时又会出现新的问题（边框四个边没有全部着色 `#333`）。

**解决方法**：`margin` 负值、`z-index`。

```css
.tabs {
  font-size: 0;
}
.tabs-tab {
  display: inline-block;
  /* + */
  position: relative;
  z-index: 0;
  margin-right: -1px;
  /* + */
  padding: 0 24px;
  border: 1px solid #e0e0e0;
  font-size: 14px;
  line-height: 32px;
  text-decoration: none;
  color: rgba(0, 0, 0, .54);
}
.tabs-tab.active,
.tabs-tab:hover {
  /* + */
  z-index: 1;
  /* + */
  border-color: #333;
  color: rgba(0, 0, 0, .87);
  background-color: #f2f2f2;
}
```
