### ISSUE TITLE
2018 年 3 月

### ISSUE THREAD

**Issue by bizhong** [bizhong/frontend#8]
# Vue 全局引入自定义组件（库）

- main.js

```javascript
// 完整引入
import Vue from 'vue';
import App from './App.vue';
import router from './router/index.js';

import LbzUI from '../lbz-ui/index.js';
Vue.use(LbzUI);

new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
});
```

```javascript
// 按需引入
import Vue from 'vue';
import App from './App.vue';
import router from './router/index.js';

import Icon from '../lbz-ui/components/icon/index.js';
import List from '../lbz-ui/components/list/index.js';
Vue.use(Icon, List);

new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
});
```

- ../lbz-ui/index.js

```javascript
import './scss/index.scss';

import Icon from './components/icon/index.js';
// ...

const components = [
  Icon,
  // ...
];

const install = function(Vue) {
  components.map(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install
};
```

- ./scss/index.scss

```scss
@import './normalize.scss';

@import './_variables.scss';
@import './_mixins.scss';

@import './lbz-icon.scss';
// ...
```

- ./components/icon/index.js

```javascript
import Icon from './lbz-icon.vue';

Icon.install = function(Vue) {
  Vue.component(Icon.name, Icon);
};

export default Icon;
```

- ./lbz-icon.vue

```vue
<template>
  <i
    class="lbz-icon"
    :class="[
      size ? 'lbz-icon--' + size : '',
      icon ? 'lbz-icon--' + icon : ''
    ]"
  ></i>
</template>

<script>
  export default {
    name: 'lbz-icon',

    props: {
      size: String, // small, (default), large
      icon: String
    }
  };
</script>
```

**Comment by bizhong** [comment]
# px、rem 转换

```scss
$--base-font-size: 16 !default;

@function parseInt($n) {
  @return $n / ($n * 0 + 1);
}

// px2rem 输入 px，输出 rem
// ==========================================================================
// px2rem(16px);

@function px2rem($px) {
  @return parseInt($px) / $--base-font-size * 1rem;
}

// rem2px 输入 rem，输出 px
// ==========================================================================
// rem2px(1rem);

@function rem2px($rem) {
  @return parseInt($rem) * $--base-font-size * 1px;
}

// pxrem 输入 px，输出 px、rem
// ==========================================================================
// @include pxrem(margin, 16px auto);

@function convertPxRem($type, $values) {
  $list: ();

  @each $value in $values {
    @if $value == 0 or type-of($value) != 'number' { $list: append($list, $value); }
    @else {
      $unit: unit($value);
      $val: parseInt($value);

      @if ($type == 0) and ($unit == 'rem') {
        $list: append($list, ($val * $--base-font-size) + px);
      }
      @else if ($type == 1) and ($unit == 'px') {
        $list: append($list, ($val / $--base-font-size) + rem);
      }
      @else {
        $list: append($list, $value);
      }
    }
  }

  @return $list();
}

@mixin pxrem($property, $value) {
  #{$property}: convertPxRem(0, $value);
  #{$property}: convertPxRem(1, $value);
}
```

**简单使用**

输入：

```scss
.lanbizhong {
  @include pxrem(margin, 16px auto .5rem);
  width: px2rem(16px);
  height: rem2px(2rem);
}
```

输出：

```css
.lanbizhong {
  margin: 16px auto 8px;
  margin: 1rem auto 0.5rem;
  width: 1rem;
  height: 32px;
}
```
